### ISSUE TITLE
metrics: Add gatewayclass metrics for status.supportedFeatures

### ISSUE THREAD

**Issue by david-martin** [Kuadrant/gateway-api-state-metrics#17]
From GEP https://github.com/kubernetes-sigs/gateway-api/pull/2163/files, a new field in the GatewayClass status is proposed.
It looks something like this:

```yaml
  supportedFeatures:
    - HTTPRoute
    - HTTPRouteHostRewrite
    - HTTPRoutePortRedirect
    - HTTPRouteQueryParamMatching
```

It would be good to have this status information captured in state metrics.
e.g.

```prometheus
gatewayapi_gatewayclass_status_supported_feature{namespace="default",name="external",feature="HTTPRoute"} 1
gatewayapi_gatewayclass_status_supported_feature{namespace="default",name="external",feature="HTTPRouteHostRewrite"} 1
...
```

cc @LiorLieberman
Did I miss anything here from your suggestion on the sig call?

**Comment by LiorLieberman** [comment]
Thanks David! For some reason i have not got notification for this mention. Just got one when you closed the issue. Anyway that looks good to me. Keep an eye on the this pr to see what would be the final changes upstream. (https://github.com/kubernetes-sigs/gateway-api/pull/2383)

**Comment by david-martin** [comment]
Thanks @LiorLieberman 
I'll will keep an eye on that PR.
